# Generated by Django 4.1.1 on 2022-10-05 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('F', 'Fashion'), ('A', 'Art'), ('N', 'Nature'), ('E', 'Eats'), ('M', 'Music'), ('S', 'Sports'), ('P', 'Pets')], default='F', max_length=1)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.post')),
            ],
        ),
    ]
